#!/usr/bin/env python3
"""Pydantic schemas for Web API."""

from price_watch.webapi.schemas.items import (
    ErrorResponse,
    EventsQueryParams,
    HistoryQueryParams,
    HistoryResponse,
    ItemEventsQueryParams,
    ItemsQueryParams,
    ItemsResponse,
    MetricsCrawlTimeQueryParams,
    MetricsFailuresQueryParams,
    MetricsHeatmapQueryParams,
    MetricsHeatmapSvgQueryParams,
    MetricsSessionsQueryParams,
    MetricsStoresQueryParams,
    Period,
    PriceHistoryPoint,
    ResultItem,
    StoreDefinition,
    StoreEntry,
)
from price_watch.webapi.schemas.target import (
    ACTION_TYPES,
    CHECK_METHODS,
    ActionStepSchema,
    CheckItemRequest,
    CheckItemResponse,
    CheckJobStatus,
    ItemDefinitionSchema,
    PreloadConfigSchema,
    StoreDefinitionSchema,
    StoreEntrySchema,
    TargetConfigResponse,
    TargetConfigSchema,
    TargetUpdateRequest,
    TargetUpdateResponse,
    ValidateResponse,
    ValidationError,
)

__all__ = [
    "ACTION_TYPES",
    "CHECK_METHODS",
    "ActionStepSchema",
    "CheckItemRequest",
    "CheckItemResponse",
    "CheckJobStatus",
    "ErrorResponse",
    "EventsQueryParams",
    "HistoryQueryParams",
    "HistoryResponse",
    "ItemDefinitionSchema",
    "ItemEventsQueryParams",
    "ItemsQueryParams",
    "ItemsResponse",
    "MetricsCrawlTimeQueryParams",
    "MetricsFailuresQueryParams",
    "MetricsHeatmapQueryParams",
    "MetricsHeatmapSvgQueryParams",
    "MetricsSessionsQueryParams",
    "MetricsStoresQueryParams",
    "Period",
    "PreloadConfigSchema",
    "PriceHistoryPoint",
    "ResultItem",
    "StoreDefinition",
    "StoreDefinitionSchema",
    "StoreEntry",
    "StoreEntrySchema",
    "TargetConfigResponse",
    "TargetConfigSchema",
    "TargetUpdateRequest",
    "TargetUpdateResponse",
    "ValidateResponse",
    "ValidationError",
]
