check:
    interval_sec: 999999999  # Very large value to ensure single execution (won't trigger another check within 20m timeout)

slack:
    bot_token: "dummy-slack-token"
    from: price-watch
    info:
        channel:
            name: "#price"
    error:
        channel:
            name: "#error"
            id: C0123456789
        interval_min: 60

store:
    amazon:
        associate: XXXXXX-22
        access_key: XXXXXXXXXXXXXXXXXXXX
        secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        host: webservices.amazon.co.jp
        region: us-west-2

    yahoo:
        client_id: XXXXXXXXXXXXXXXXXXXX
        secret: XXXXXXXXXXXXXXXXXXXX

data:
    selenium: ./data
    dump: ./data/debug
    price: ./data/price
    thumb: ./data/thumb
    metrics: ./data/metrics
    cache: ./data/cache

target:
    define: target.yaml

liveness:
    file:
        crawler: /dev/shm/healthz
    interval_sec: 300

webapp:
    static_dir_path: frontend/dist

edit:
    password_hash: "$argon2id$v=19$m=65536,t=3,p=4$G3sQ/+Jkh/ufAWCJDUTaPw$8wl44G3QrQysWT9mIDLD3bf0fLn0o/RO1EnYVVovyLs"
