check:
    interval_sec: 21600  # 6時間ごと

slack:
    bot_token: "xoxb-dummy"  # Discord利用のため不使用
    from: "price-watch"

data:
    selenium: ./data
    dump: ./data/debug
    price: ./data/price
    thumb: ./data/thumb
    metrics: ./data/metrics
    cache: ./data/cache

target:
    define: target.yaml

liveness:
    file:
        crawler: /tmp/healthz
    interval_sec: 300

edit:
    password_hash: "$argon2id$v=19$m=65536,t=3,p=4$G3sQ/+Jkh/ufAWCJDUTaPw$8wl44G3QrQysWT9mIDLD3bf0fLn0o/RO1EnYVVovyLs"

webapp: {}
